name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    # TODO: Use dart publish reusable workflow, see https://github.com/dart-lang/setup-dart/issues/68
    # https://github.com/dart-lang/setup-dart/blob/main/.github/workflows/publish.yml
    name: 'Publish to pub.dev'
    environment: 'pub.dev'
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup Dart SDK with JWT token
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: dart pub get
      - name: Publish - dry run
        run: dart pub publish --dry-run
      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
