name: pull-request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  call-test:
    uses: ./.github/workflows/test.yml
    if: ${{ github.event.pull_request.draft == false }}
