name: test example
on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter Version'
        required: false
        default: '3.16.x'
        type: string
  workflow_call:
    inputs:
      flutter_version:
        required: false
        default: '3.16.x'
        type: string

jobs:
  debian:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: 'stable'
      - name: Activate flutter_to_debian
        run: dart pub global activate --source path ./
      - name: Install Flutter requirements for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Example app - Build Debian app
        working-directory: ./example
        run: |
          flutter build linux
          flutter_to_debian
          [ -f "build/linux/x64/release/debian/example_1.0.0_amd64.deb" ] && exit 0 || exit 1
